#!/usr/bin/env bash
# Generate public/src/config.js from environment variables.
# Source of values (in priority order):
#   1. SUPABASE_URL / SUPABASE_ANON_KEY already exported in the shell
#   2. a .env file in the repo root (KEY=value lines)
#
# config.js is gitignored; the anon key it contains is public-safe (RLS protects
# data), but we still generate rather than commit so local/prod values stay separate.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT="$ROOT/public/src/config.js"

# Load .env if the vars aren't already in the environment.
if [[ -z "${SUPABASE_URL:-}" || -z "${SUPABASE_ANON_KEY:-}" ]]; then
  if [[ -f "$ENV_FILE" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
  fi
fi

: "${SUPABASE_URL:?Set SUPABASE_URL (in .env or the shell)}"
: "${SUPABASE_ANON_KEY:?Set SUPABASE_ANON_KEY (in .env or the shell)}"

cat > "$OUT" <<EOF
// AUTO-GENERATED by scripts/gen-config.sh — do not edit. Values are public-safe.
export const SUPABASE_URL = "${SUPABASE_URL}";
export const SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}";
EOF

echo "wrote $OUT"
